import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header";
import Form from "@/components/Form";
import PostFeed from "@/components/posts/PostFeed";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>MIPA TWITTER</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header label="Home"></Header>
      <Form placeholder="What's happening?" />
      <PostFeed />
      <main className={"bg-white"}></main>
    </>
  );
}
